/**
 * Moments art: soft-3D clay characters/dioramas and e-commerce product shots, generated on
 * Vertex AI (project davelabs-tools) with the Gemini image model — the same pipeline Optiq
 * uses (optiq/scripts/generate-enterprise-assets.mjs). Idempotent: existing files are skipped.
 *
 *   node scripts/gen-art.mjs                      # everything in art-manifest.json
 *   node scripts/gen-art.mjs --only a,b           # just these keys (style probes)
 *   node scripts/gen-art.mjs --ref cover-rooftop-30th   # style-reference an approved image
 *   node scripts/gen-art.mjs --index              # only rebuild src/data/art-index.generated.ts
 *
 * Auth: GOOGLE_APPLICATION_CREDENTIALS (defaults to Optiq's service account; never copied here).
 */
import { GoogleAuth } from 'google-auth-library';
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const ART = path.join(ROOT, 'assets', 'art');
const INDEX = path.join(ROOT, 'src', 'data', 'art-index.generated.ts');
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts', 'art-manifest.json'), 'utf8'));

process.env.GOOGLE_APPLICATION_CREDENTIALS ||= 'C:\\Projects\\optiq\\secrets\\davelabs-tools-sa.json';
const PROJECT = process.env.GOOGLE_CLOUD_PROJECT || 'davelabs-tools';
const MODELS = [process.env.IMAGE_MODEL, 'gemini-3-pro-image', 'gemini-3-pro-image-preview', 'gemini-3.1-flash-image'].filter(Boolean);

const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const only = flag('--only')?.split(',');
const refKey = flag('--ref');
const force = args.includes('--force');
const indexOnly = args.includes('--index');

const auth = new GoogleAuth({ scopes: 'https://www.googleapis.com/auth/cloud-platform' });
const token = async () => (await (await auth.getClient()).getAccessToken()).token;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const url = (model) => `https://aiplatform.googleapis.com/v1beta1/projects/${PROJECT}/locations/global/publishers/google/models/${model}:generateContent`;

const SIZES = { '4:3': [1200, 900], '3:4': [768, 1024], '1:1': [800, 800], '9:16': [900, 1600] };
const fileFor = (item) => path.join(ART, item.dir, `${item.key}.webp`);

let model = MODELS[0];

async function generate(body, label) {
  for (let attempt = 1; ; attempt++) {
    let res;
    try {
      res = await fetch(url(model), {
        method: 'POST',
        headers: { Authorization: `Bearer ${await token()}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
    } catch (e) {
      if (attempt >= 4) throw e;
      await sleep(5000);
      continue;
    }
    if (res.ok) return res.json();
    const text = await res.text();
    if (res.status === 404 && MODELS.indexOf(model) < MODELS.length - 1) {
      const next = MODELS[MODELS.indexOf(model) + 1];
      console.log(`    · ${model} not available (404) — falling back to ${next}`);
      model = next;
      attempt = 0;
      continue;
    }
    if ((res.status === 429 || res.status === 503) && attempt < 4) {
      const wait = res.status === 429 ? 35000 : 6000;
      console.log(`    · ${res.status} on ${label}; waiting ${wait / 1000}s (retry ${attempt}/4)`);
      await sleep(wait);
      continue;
    }
    throw new Error(`${label} → ${res.status}: ${text.slice(0, 240)}`);
  }
}

/** Average colour of the four corners — cards sit on this so there's no seam. */
async function cornerColour(buf) {
  const { data, info } = await sharp(buf).resize(64, 64, { fit: 'fill' }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const px = (x, y) => {
    const i = (y * info.width + x) * 3;
    return [data[i], data[i + 1], data[i + 2]];
  };
  const pts = [];
  for (const [cx, cy] of [
    [2, 2],
    [61, 2],
    [2, 61],
    [61, 61],
  ])
    for (let dx = -1; dx <= 1; dx++) for (let dy = -1; dy <= 1; dy++) pts.push(px(cx + dx, cy + dy));
  const avg = [0, 1, 2].map((k) => Math.round(pts.reduce((s, p) => s + p[k], 0) / pts.length));
  return `#${avg.map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase()}`;
}

function writeIndex() {
  const metaPath = path.join(ART, 'meta.json');
  const meta = fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, 'utf8')) : {};
  const rows = manifest.items
    .filter((it) => fs.existsSync(fileFor(it)))
    .map((it) => {
      const rel = `@/assets/art/${it.dir}/${it.key}.webp`;
      const bg = meta[it.key]?.bg ?? it.bg;
      return `  '${it.key}': { source: require('${rel}'), bg: ${bg ? `'${bg}'` : 'undefined'} },`;
    });
  fs.writeFileSync(
    INDEX,
    `// Generated by scripts/gen-art.mjs — maps art keys to bundled images and their measured\n// background colours. Re-run \`node scripts/gen-art.mjs --index\` after adding images.\nimport type { ImageSource } from 'expo-image';\n\nexport const artIndex: Record<string, { source: ImageSource | number; bg?: string }> = {\n${rows.join('\n')}\n};\n`,
  );
  console.log(`index → ${rows.length} images`);
}

async function main() {
  if (indexOnly) return writeIndex();
  const metaPath = path.join(ART, 'meta.json');
  fs.mkdirSync(ART, { recursive: true });
  const meta = fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, 'utf8')) : {};

  let refPart = null;
  if (refKey) {
    const ref = manifest.items.find((i) => i.key === refKey);
    if (!ref || !fs.existsSync(fileFor(ref))) throw new Error(`reference ${refKey} not found — generate it first`);
    const png = await sharp(fileFor(ref)).png().toBuffer();
    refPart = { inlineData: { mimeType: 'image/png', data: png.toString('base64') } };
    console.log(`style reference: ${refKey}`);
  }

  const todo = manifest.items.filter((i) => (!only || only.includes(i.key)) && (force || !fs.existsSync(fileFor(i))));
  console.log(`generating ${todo.length} image(s) with ${model}`);
  for (const item of todo) {
    const style = manifest.style[item.style].replace('{bg}', item.bg ?? '#FFFFFF');
    const useRef = refPart && item.style === 'clay' && item.key !== refKey;
    const text = useRef
      ? `Match the art style of the reference image exactly — the same clay material, lighting, grain, softness and palette — but draw a completely new subject: ${item.prompt}. ${style}`
      : `${item.prompt}. ${style}`;
    console.log(`  … ${item.key}`);
    try {
      const data = await generate(
        {
          contents: [{ role: 'user', parts: useRef ? [refPart, { text }] : [{ text }] }],
          generationConfig: { responseModalities: ['TEXT', 'IMAGE'], imageConfig: { aspectRatio: item.aspect } },
        },
        item.key,
      );
      const inline = data.candidates?.[0]?.content?.parts?.find((p) => p.inlineData)?.inlineData;
      if (!inline?.data) throw new Error('no image returned');
      const raw = Buffer.from(inline.data, 'base64');
      const [w, h] = SIZES[item.aspect];
      fs.mkdirSync(path.dirname(fileFor(item)), { recursive: true });
      const out = await sharp(raw).resize(w, h, { fit: 'cover' }).webp({ quality: 84 }).toBuffer();
      fs.writeFileSync(fileFor(item), out);
      meta[item.key] = { bg: item.style === 'product' ? '#FFFFFF' : await cornerColour(raw), model };
      fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2));
      console.log(`  ✓ ${item.key} (${Math.round(out.length / 1024)} KB, bg ${meta[item.key].bg})`);
    } catch (e) {
      console.error(`  ✗ ${item.key}: ${e.message}`);
    }
    await sleep(12000);
  }
  writeIndex();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
